name: Infinitivve Checker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Checkout RQT
      uses: actions/checkout@master
      with:
        repository: pumperknickle/RQTAPI
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r RQTAPI/requirements.txt
        
    - name: Install Language Model
      run: |
        python -m spacy download en_core_web_sm
        
    - name: Run RQT
      run: |
        python RQTAPI/ReportGenerator.py "$PWD"
    
    - name: Upload Report
      uses: actions/upload-artifact@v1
      with:
        name: infinitive report
        path: RQT_report.html
        
    
